language: node_js
node_js:
  - "iojs"
  - "9"
install:
- pip install --user awscli
before_script:
  - npm install --global gatsby-cli
script:
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: yTFA+QtXzXX9e7+mBH0BtNXNFcAOWbraJEAS+Eu/0ZeXoXa5oyWPl20esHMFLzPmibu9j7083Y/wyQgxtChklqNRzkVDu+/D9D+gub7tgFY9iPc2HyZc6ncUVwdk74DkKw4csbFH0+6ls+v9ngjYp7HXiGcd4PXmb6xWc+pUNLCrpfOcnRoIRkeZvR8M5VVrOZOwNCddeo9yphMyLy4fLxPy2mM+jrsTnZOaCQV5vh8VhrN/LBnSZSc3/xEdlEZKWUa7GkxcSc7/Nn8w7jzf+mdkooZmRDrtktFVN5UGd5QxALar9nd40vlUNFc6tnQ55FHy3s3SaC0PoulpnaIKBh5WW5t+H63Bm4Upanv5CEdwQHtOussKXT7EeWMFAJdDIW/mVkS+FzxBU8HvMvNxcIMlYg9Hmckupaq3EQyOMsZcokzr6fWgEdMb+jT3zo8BYvI2lEEQT/JZDyjKa3Xz9eBOXf9AmLUCTLr8xqGVuawKV5dcV4HfbY4BzWi1Cd4zG9iWyK+MsCzX6I6lbVG8EEPy5TauTHvQgrrkSLWBg1zK54md4RND0bz9Wd5l8yvYTPoksjHQGkRBwJWPtYbvpijo6EaATpaT16wKqoFEAtA7PS122UckINcMoed1RUQdeZlk5ePICQHEDJ2+oVHhVJlWyvJaDc+JFNMoMuDcmII=
  - secure: vyfFLL/NdpUk4Ilslb67C2vMxByfIx8b2UbdVe6PB+9rCNIcO7uvRVHc7mHbb2PbroTxMNAWS4ewPEjbrUVu0lJfuV/aBzzL6smMl9YwR2G7TwMW9nigYkN475YMpMUGF8vMTVHD0QMweQpIwviqoryLGJZnpwj+A6b0OdOPD+jJqm6kMchiKGSUAPZWH9VQ59dkRoYiSqiWuau+F1Qj6cDtppbJa9EofM7X08AGExcxVkEPXAX1xuMHm7X88rKwtrpJ6h4vmZKipKIGFyr/ZhkwhgzL2XdnUMwSKtwsvwwSWCYOyUunxvspweVgBTRgg7vwyOhiA6mk676qiZEmL4mgybxFbIBB/IjEETP339SsLXY4ryS1+MxgqjSoY4ep9FPKeR4BmjFAcx+BGJDyDpKc+EtxYeRIE3u9dzCwop6vrFjsgKciVPYzScoVgh4tPmtNgGnrjv1nAwgNzknKOkxP4XyEiUTeYC09+2mp17XUi8O63kADdydWk+/2VTZJzUPS4Lfq6KeagKLZxAYj5uq+VSmY9RCKuK0qOjh41/kqVSRqx9H9cw79dGFhhKlfW49T3f/Hz16ER6wtfi2zBWF2mFsC2zt7Yw+mtFQjxKiijt0s9/+/lliI8jSer+FTlAAyHx+Taxb4rP6U1y9xKEODEUZpNBkr9ro9SvT5Zhg=
