language: node_js
node_js:
- '9'
install:
- pip install --user awscli
before_script:
- npm install --global gatsby-cli
script:
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: EWH3WvzX3U1nzpUseXs0yz6ni2D0BbP5Q4csfm9tlUpoahgS1/trL6q0ISxCe+cL+6bixeWV892JB5vVyxE1hneGbhchrqeAhGzjOPELkz6nImWmJUnWgX4tYE8bhsLJXozTM2a5EDluppwUNwXl9BDlO8DEsqww5OAxz4IXI/XgXvilPE96OyFVguP/u5sD+2sqtN5Q4EXSgO6QRnPf3pcqcrHsEmYmlojMANyB5WYjM+gIexxCTG53qB+peniDR6gxO6Jx0UugokqFXI5W5abrwnXKFFHkPMMLMb7BUprytOzoc4e1L3ihYqRzBjKakR9Bt2BVOqaLWj6C+kAsoxwTAw/oibvCrZ6aSNZ8d44oHLHfFlQFxHTVu8sqOG7UHFLQHLUEpxxQFV27pe1BFixBz7Q4YGFNYJEb73uurW7p8CtZFmhVYhRJkPhqY5OXgqrexywvCr+KNtNJVkclkHDoyhJQpNV+XWnEHKpGx9QdO0JIiWDPGK4qAgzZQzhHGjqXXgwHxJnr1KD0xzEWF+uUZTRUF/+ZjwFTC1JKTkwnIauiJtnDsOeBLt2TBJOqodDime78lPedgqI+f6bodPun0MHB88WhcUSQVPXcey2w6M8YzAV5P15LI5kvDFVTARlG3TJc6x4gO+plsjDNfc30UvBmSKc54NLA+UJdRh8=
  - secure: Fb472mXGgPUQB8qh+6VNJew+icW0EvHuXWbVNIY3ZeS9Xg5lEnnnjrZUZ1uuoIX4/k28A15cp4ExQiSDWGWgrSikY8ZbzouO3wZnYm05YuS+ThIpHqj9G/FY6uMvoNVlNvUZvLEiAybPwD/UlXqkVo0bqcawHMNYSoCBFTBJSHTQ3aJAZjDb1/BM8PgYtAfAw6F2q5mZm03HH9rAPqIxm81AEFcmQgMhFG+jsw8UHhkpqlw/RToSHD5f3GZXjOgXjEecEyUxguLaqRJKXV/f8IqHRzpN8MGzIMCzEMPJ/cU3dlFCG2RxFsDm7kaCeAlAtPK/h7RBZR/iXIoisXiS0wWjFYiSqHpZoVHVp1xIlQyoktOUefNiJzBG41/HMeOt2d4FMAqiHv/CLEpSPsjLgTXtdTTGuPOLIigI6UNkHinFwdIaRHJIA1Rx2lQLkcEddPjm+0zlhjbnQFNKQhjoYRXjbxjBSCz8IjopTZHOszkExxoGFGEZEvMm2M9d/KzSHrN6W2qpRLJgVsMzRS8Xbu2BlKgfAga/XV9loTU0/TLP3MVg6k9HQ+EJrqoCd71DSAYz/5V/qALvEd0LKEtEm9DJ7cfTVKHEGcqriAMWegmHTrqWpQKKNDkkobCfizEisK21heiTfjNqvLxjAtpIQuFeOr5akH5m3Sb3XJ40Y4I=
